[pytest]
testpaths    = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --tb=short
    --alluredir=reports/allure-results


log_cli       = true
log_cli_level = INFO
log_format    = %(asctime)s [%(levelname)-8s] %(name)s: %(message)s
log_date_format = %H:%M:%S


markers =
    ui:       Pure UI tests (Selenium)
    api:      Pure API tests (requests)
    e2e:      Hybrid end-to-end tests
    negative: Negative / boundary test cases
    slow:     Tests that take longer than average
    delete:   Tests for deleting notes